// teams.js
// This file contains the list of clubs shown on the map.
// Add, remove, or edit entries here as needed.

const teams = [
  {
    "id": "ARS-EN-EM-NE2U",
    "club": "Arsenal",
    "teamName": "Arsenal WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.5557298,
    "lng": -0.1083118,
    "groundName": "Emirates Stadium",
    "groundLabel": "Emirates Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.arsenal.com/women",
    "instagram": "https://www.instagram.com/arsenalwfc/",
    "twitter": "https://x.com/ArsenalWFC",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "ARS-EN-BO-WXM7",
    "club": "Arsenal",
    "teamName": "Arsenal WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-EE",
    "regionName": "East of England",
    "lat": 51.6621617,
    "lng": -0.2712835,
    "groundName": "Borehamwood Football Club",
    "groundLabel": "Borehamwood Football Club",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.arsenal.com/women",
    "instagram": "https://www.instagram.com/arsenalwfc/",
    "twitter": "https://x.com/ArsenalWFC",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "AST-EN-VI-CCK6",
    "club": "Aston Villa",
    "teamName": "Aston Villa WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-WM",
    "regionName": "West Midlands",
    "lat": 52.5091117,
    "lng": -1.8847828,
    "groundName": "Villa Park",
    "groundLabel": "Villa Park",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.avfc.co.uk/Teams/womens/",
    "instagram": "https://www.instagram.com/avwfcofficial/",
    "twitter": "https://x.com/AVWFCOfficial",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "AST-EN-BE-YAZJ",
    "club": "Aston Villa",
    "teamName": "Aston Villa WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-WM",
    "regionName": "West Midlands",
    "lat": 52.5657831,
    "lng": -1.9906229,
    "groundName": "Bescot Stadium",
    "groundLabel": "Walsall FC Poundland Bescot Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.avfc.co.uk/Teams/womens/",
    "instagram": "https://www.instagram.com/avwfcofficial/",
    "twitter": "https://x.com/AVWFCOfficial",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BRI-EN-BR-W6CH",
    "club": "Brighton & Hove Albion",
    "teamName": "Brighton & Hove Albion WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-SE",
    "regionName": "South East",
    "lat": 51.099807,
    "lng": -0.1948115,
    "groundName": "Broadfield Stadium",
    "groundLabel": "Broadfield Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.brightonandhovealbion.com/teams/womens-team",
    "instagram": "https://www.instagram.com/bhafcwomen/",
    "twitter": "https://x.com/BHAFCWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BRI-EN-AM-TM0E",
    "club": "Brighton & Hove Albion",
    "teamName": "Brighton & Hove Albion WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-SE",
    "regionName": "South East",
    "lat": 50.8615724,
    "lng": -0.0836618,
    "groundName": "American Express Stadium",
    "groundLabel": "American Express Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.brightonandhovealbion.com/teams/womens-team",
    "instagram": "https://www.instagram.com/bhafcwomen/",
    "twitter": "https://x.com/BHAFCWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "CHE-EN-KI-QXUI",
    "club": "Chelsea",
    "teamName": "Chelsea WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.405267,
    "lng": -0.2818903,
    "groundName": "Kingsmeadow",
    "groundLabel": "Kingsmeadow",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.chelseafc.com/en/teams/chelsea-women",
    "instagram": "https://www.instagram.com/chelseafcw/",
    "twitter": "https://x.com/ChelseaFCW",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "CHE-EN-ST-9AI3",
    "club": "Chelsea",
    "teamName": "Chelsea WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.4817241,
    "lng": -0.1909471,
    "groundName": "Stamford Bridge",
    "groundLabel": "Stamford Bridge",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.chelseafc.com/en/teams/chelsea-women",
    "instagram": "https://www.instagram.com/chelseafcw/",
    "twitter": "https://x.com/ChelseaFCW",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "CRY-EN-VB-EI18",
    "club": "Crystal Palace",
    "teamName": "Crystal Palace WFC",
    "sport": "football",
    "code": null,
    "tier": "tier2",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.3677754,
    "lng": -0.2042941,
    "groundName": "VBS Community Stadium",
    "groundLabel": "Crystal Palace -Â  VBS Community Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.cpfc.co.uk/palace-women/",
    "instagram": "https://www.instagram.com/cpfc_w/",
    "twitter": "https://x.com/cpfc_w",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "CRY-EN-SE-7MBF",
    "club": "Crystal Palace",
    "teamName": "Crystal Palace WFC",
    "sport": "football",
    "code": null,
    "tier": "tier2",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.3981495,
    "lng": -0.0857056,
    "groundName": "Selhurst Park",
    "groundLabel": "Selhurst Park",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.cpfc.co.uk/palace-women/",
    "instagram": "https://www.instagram.com/cpfc_w/",
    "twitter": "https://x.com/cpfc_w",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "EVE-EN-WA-U3FZ",
    "club": "Everton",
    "teamName": "Everton WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.445356,
    "lng": -2.9536821,
    "groundName": "Walton Hall Park",
    "groundLabel": "Walton Hall Park",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.evertonfc.com/women",
    "instagram": "https://www.instagram.com/evertonwomen/",
    "twitter": "https://x.com/EvertonWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "EVE-EN-GO-BUZM",
    "club": "Everton",
    "teamName": "Everton WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4388437,
    "lng": -2.9662821,
    "groundName": "Goodison Park",
    "groundLabel": "Goodison Park",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.evertonfc.com/women",
    "instagram": "https://www.instagram.com/evertonwomen/",
    "twitter": "https://x.com/EvertonWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LEI-EN-KI-597M",
    "club": "Leicester City",
    "teamName": "Leicester City WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-EM",
    "regionName": "East Midlands",
    "lat": 52.6203662,
    "lng": -1.1421895,
    "groundName": "King Power Stadium",
    "groundLabel": "King Power Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.lcfc.com/women",
    "instagram": "https://www.instagram.com/lcfcwomen/",
    "twitter": "https://x.com/LCFC_Women",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LEI-EN-PI-XHHW",
    "club": "Leicester City",
    "teamName": "Leicester City WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-WM",
    "regionName": "West Midlands",
    "lat": 52.8215623,
    "lng": -1.627267,
    "groundName": "Pirelli Stadium Princess Way",
    "groundLabel": "Pirelli Stadium Princess Way",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.lcfc.com/women",
    "instagram": "https://www.instagram.com/lcfcwomen/",
    "twitter": "https://x.com/LCFC_Women",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LIV-EN-TO-2R9Y",
    "club": "Liverpool",
    "teamName": "Liverpool WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4474676,
    "lng": -2.7261145,
    "groundName": "Totally Wicked Stadium",
    "groundLabel": "Totally Wicked Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.liverpoolfc.com/team/womens",
    "instagram": "https://www.instagram.com/liverpoolfcw/",
    "twitter": "https://x.com/LiverpoolFCW",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LIV-EN-AN-88SD",
    "club": "Liverpool",
    "teamName": "Liverpool WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4308435,
    "lng": -2.9608174,
    "groundName": "Anfield",
    "groundLabel": "Anfield",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.liverpoolfc.com/team/womens",
    "instagram": "https://www.instagram.com/liverpoolfcw/",
    "twitter": "https://x.com/LiverpoolFCW",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "MAN-EN-JO-BWKJ",
    "club": "Manchester City",
    "teamName": "Manchester City WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4809677,
    "lng": -2.1926539,
    "groundName": "Joie Stadium",
    "groundLabel": "Joie Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.mancity.com/manchester-city-women",
    "instagram": "https://www.instagram.com/mancitywomen",
    "twitter": "https://x.com/ManCityWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "MAN-EN-ET-4NS8",
    "club": "Manchester City",
    "teamName": "Manchester City WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4831634,
    "lng": -2.2003736,
    "groundName": "Etihad Stadium",
    "groundLabel": "Etihad Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.mancity.com/manchester-city-women",
    "instagram": "https://www.instagram.com/mancitywomen",
    "twitter": "https://x.com/ManCityWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "MAN-EN-LE-UNKG",
    "club": "Manchester United",
    "teamName": "Manchester United WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4899532,
    "lng": -2.5309793,
    "groundName": "Leigh Sports Village",
    "groundLabel": "Leigh Sports Village",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.manutd.com/en/news/women",
    "instagram": "https://www.instagram.com/manutdwomen/",
    "twitter": "https://x.com/ManUtdWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "MAN-EN-OL-JMMB",
    "club": "Manchester United",
    "teamName": "Manchester United WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4630589,
    "lng": -2.2913401,
    "groundName": "Old Trafford",
    "groundLabel": "Old Trafford",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.manutd.com/en/news/women",
    "instagram": "https://www.instagram.com/manutdwomen/",
    "twitter": "https://x.com/ManUtdWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "TOT-EN-BR-EQ0T",
    "club": "Tottenham Hotspur",
    "teamName": "Tottenham Hotspur WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.5601583,
    "lng": -0.0126087,
    "groundName": "Brisbane Lane",
    "groundLabel": "Brisbane Lane",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.tottenhamhotspur.com/teams/women/players/",
    "instagram": "https://www.instagram.com/spurswomen/",
    "twitter": "https://x.com/SpursWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "TOT-EN-TO-TYO5",
    "club": "Tottenham Hotspurs",
    "teamName": "Tottenham Hotspurs WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.6042205,
    "lng": -0.0662231,
    "groundName": "Tottenham Hotspur Stadium",
    "groundLabel": "Tottenham Hotspur Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.tottenhamhotspur.com/teams/women/players/",
    "instagram": "https://www.instagram.com/spurswomen/",
    "twitter": "https://x.com/SpursWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "WES-EN-CH-LK96",
    "club": "West Ham Women",
    "teamName": "West Ham WFC",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.5473022,
    "lng": 0.1600155,
    "groundName": "Chigwell Construction Stadium",
    "groundLabel": "Chigwell Construction Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.whufc.com/women/womens-team",
    "instagram": "https://www.instagram.com/westhamwomen/",
    "twitter": "https://x.com/westhamwomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LON-EN-CO-4GUE",
    "club": "London City Lionesses",
    "teamName": "London City Lionesses",
    "sport": "football",
    "code": null,
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.39046639,
    "lng": 0.021316266,
    "groundName": "Copperjax Community Stadium",
    "groundLabel": "Copperjax Community Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.londoncitylionesses.com/",
    "instagram": "https://www.instagram.com/londoncitylionesses/",
    "twitter": "https://twitter.com/LC_Lionesses",
    "streaming": null,
    "otherSocials": "https://www.youtube.com/@londoncitylionesses, https://www.facebook.com/LondonCityLionesses, https://www.tiktok.com/@londoncitylionesses"
  },
  {
    "id": "BRI-EN-SH-1JAW",
    "club": "Bristol Bears",
    "teamName": "Bristol Bears Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-SW",
    "regionName": "South West",
    "lat": 51.4980888,
    "lng": -2.5299069,
    "groundName": "Shaftesbury Park",
    "groundLabel": "Shaftesbury Park",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/bristolbearswomen/",
    "twitter": "https://twitter.com/BristolBearsW",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/BristolBearsW"
  },
  {
    "id": "EXE-EN-SA-NXPI",
    "club": "Exeter Chiefs",
    "teamName": "Exeter Chiefs Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-SW",
    "regionName": "South West",
    "lat": 50.7095567,
    "lng": -3.4683403,
    "groundName": "Sandy Park",
    "groundLabel": "Sandy Park",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/exechiefswomen/",
    "twitter": "https://twitter.com/ExeChiefsWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/ExeterChiefsWomen"
  },
  {
    "id": "EAL-EN-EA-0XLU",
    "club": "Ealing Trailfinders",
    "teamName": "Ealing Trailfinders Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.5247325,
    "lng": -0.3293985,
    "groundName": "Ealing Trailfinders Rugby Club",
    "groundLabel": "Ealing Trailfinders Rugby Club",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/trailfinderswomen/",
    "twitter": "https://twitter.com/TrailfindersW",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/EalingTrailfindersWomensRugby"
  },
  {
    "id": "GLO-EN-TH-JA58",
    "club": "Gloucester-Hartpury",
    "teamName": "Gloucester-Hartpury Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-SW",
    "regionName": "South West",
    "lat": 51.9037018,
    "lng": -2.3025382,
    "groundName": "The Hartpury Arena",
    "groundLabel": "The Hartpury Arena",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/gloucesterhartpury",
    "twitter": "https://twitter.com/gloshartpury",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/gloucesterhartpury/"
  },
  {
    "id": "GLO-EN-KI-2HM9",
    "club": "Gloucester-Hartpury",
    "teamName": "Gloucester-Hartpury Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-SW",
    "regionName": "South West",
    "lat": 51.8711897,
    "lng": -2.2428512,
    "groundName": "Kingsholm Stadium",
    "groundLabel": "Kingsholm Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/gloucesterhartpury",
    "twitter": "https://twitter.com/gloshartpury",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/gloucesterhartpury/"
  },
  {
    "id": "HAR-EN-TW-BR4O",
    "club": "Harlequins",
    "teamName": "Harlequins Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.4504131,
    "lng": -0.3441495,
    "groundName": "Twickenham Stoop",
    "groundLabel": "Twickenham Stoop",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/harlequinswomen/",
    "twitter": "https://twitter.com/HarlequinsWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/harlequinsladies"
  },
  {
    "id": "HAR-EN-SU-9UI2",
    "club": "Harlequins",
    "teamName": "Harlequins Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-SE",
    "regionName": "South East",
    "lat": 51.2353024,
    "lng": -0.6071427,
    "groundName": "Surrey Sports Park",
    "groundLabel": "Surrey Sports Park",
    "groundRole": "secondary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/harlequinswomen/",
    "twitter": "https://twitter.com/HarlequinsWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/harlequinsladies"
  },
  {
    "id": "LEI-EN-MA-XW92",
    "club": "Leicester Tigers",
    "teamName": "Leicester Tigers Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-EM",
    "regionName": "East Midlands",
    "lat": 52.6241667,
    "lng": -1.1330556,
    "groundName": "Mattioli Woods Welford Road Stadium",
    "groundLabel": "Mattioli Woods Welford Road Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/tigerswomens",
    "twitter": "https://twitter.com/TigersWomens",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/tigerswomens"
  },
  {
    "id": "LOU-EN-CI-UR2D",
    "club": "Loughborough Lightning",
    "teamName": "Loughborough Lightning Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-EM",
    "regionName": "East Midlands",
    "lat": 52.2396946,
    "lng": -0.919472,
    "groundName": "cinch Stadium",
    "groundLabel": "cinch Stadium at Franklin's Gardens",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/lightningrugby/",
    "twitter": "https://twitter.com/LightningRugby",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/LightningRugby"
  },
  {
    "id": "SAL-EN-HE-48GT",
    "club": "Sale Sharks Women",
    "teamName": "Sale Sharks Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4160883,
    "lng": -2.3212665,
    "groundName": "Heywood Road",
    "groundLabel": "Heywood Road",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/salesharkswomen/",
    "twitter": "https://twitter.com/SaleSharksWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/salesharkswomen"
  },
  {
    "id": "SAR-EN-ST-V8G8",
    "club": "Saracens",
    "teamName": "Saracens Women",
    "sport": "rugby",
    "code": "union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.6030216,
    "lng": -0.2235209,
    "groundName": "StoneX Stadium",
    "groundLabel": "StoneX Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/saracenswomen/",
    "twitter": "https://twitter.com/SaracensWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/saracenswomen"
  },
  {
    "id": "WIG-BE--2-D6IW",
    "club": "Wigan Warriors",
    "teamName": "Wigan Warriors Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier1",
    "division": "Betfred Women's Super League",
    "country": "ENG",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.547476,
    "lng": -2.6542487,
    "groundName": "Wigan Warriors RLFC",
    "groundLabel": "Wigan Warriors RLFC",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "ST.-BE--2-BHCS",
    "club": "St. Helens",
    "teamName": "St. Helens Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier1",
    "division": "Betfred Women's Super League",
    "country": "ENG",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4474676,
    "lng": -2.7261145,
    "groundName": "Totally Wicked Stadium",
    "groundLabel": "Totally Wicked Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.saintsrlfc.com/teams/sthelens-women/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LEE-BE--1-UWJ2",
    "club": "Leeds Rhinos",
    "teamName": "Leeds Rhinos Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier1",
    "division": "Betfred Women's Super League",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.8163563,
    "lng": -1.5822247,
    "groundName": "AMT Headingley Rugby Stadium",
    "groundLabel": "AMT Headingley Rugby Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.therhinos.co.uk/teams/women",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "YOR-BE--1-AIXX",
    "club": "York Valkyries",
    "teamName": "York Valkyries Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier1",
    "division": "Betfred Women's Super League",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.984315,
    "lng": -1.0529186,
    "groundName": "LNER Community Stadium",
    "groundLabel": "LNER Community Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.yorkrlfc.com/valkyrie-squad",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "WAR-BE--2-0GV4",
    "club": "Warrington Wolves",
    "teamName": "Warrington Wolves Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier1",
    "division": "Betfred Women's Super League",
    "country": "ENG",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.3950019,
    "lng": -2.5955867,
    "groundName": "The Halliwell Jones Stadium",
    "groundLabel": "The Halliwell Jones Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://warringtonwolves.com/teams/womens/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BAR-BE--3-9YXY",
    "club": "Barrow Raiders",
    "teamName": "Barrow Raiders Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier1",
    "division": "Betfred Women's Super League",
    "country": "ENG",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 54.1149128,
    "lng": -3.2353181,
    "groundName": "Craven Park",
    "groundLabel": "Craven Park",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.barrowrlfc.com/category/raiders-ladies/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "HUD-BE--1-ZRIV",
    "club": "Huddersfield Giants",
    "teamName": "Huddersfield Giants Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier1",
    "division": "Betfred Women's Super League",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.6589993,
    "lng": -1.8478935,
    "groundName": "Huddersfield Laund Hill RUFC",
    "groundLabel": "Huddersfield Laund Hill RUFC",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.giantsrl.com/locker-room/giants-women",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "FEA-BE--1-WOOH",
    "club": "Featherstone Rovers",
    "teamName": "Featherstone Rovers Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier1",
    "division": "Betfred Women's Super League",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.6785928,
    "lng": -1.3548137,
    "groundName": "Millenium Stadium",
    "groundLabel": "Millenium Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.featherstonerovers.co.uk/womens/squad/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BRA-RF--1-BL64",
    "club": "Bradford Bulls",
    "teamName": "Bradford Bulls Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.764949,
    "lng": -1.7571259,
    "groundName": "Bartercard Odsal Stadium",
    "groundLabel": "Bartercard Odsal Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.bradfordbulls.co.uk/squads/womens",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "CAS-RF--1-2NL0",
    "club": "Castleford Tigers",
    "teamName": "Castleford Tigers Rugby Ground Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.7296568,
    "lng": -1.3409352,
    "groundName": "The Jungle",
    "groundLabel": "The Jungle",
    "groundRole": "primary",
    "notes": null,
    "website": "https://castlefordtigers.com/women.php",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "SAL-RF--2-X539",
    "club": "Salford Red Devil",
    "teamName": "Salford Red Devil Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4696274,
    "lng": -2.3759139,
    "groundName": "Salford Community Stadium",
    "groundLabel": "Salford Community Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://salfordreddevils.net/team/womens-team-2/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LEI-RF--2-T9GA",
    "club": "Leigh Leopards",
    "teamName": "Leigh Leopards Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.4955622,
    "lng": -2.5269004,
    "groundName": "Twist Lane",
    "groundLabel": "Twist Lane",
    "groundRole": "primary",
    "notes": "One ground used.",
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LEI-RF--2-VUBA",
    "club": "Leigh Leopards",
    "teamName": "Leigh Leopards Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.489545,
    "lng": -2.5301807,
    "groundName": "Leigh Sports Village",
    "groundLabel": "Leigh Sports Village",
    "groundRole": "secondary",
    "notes": "One ground used.",
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "HUL-RF--0-BSL5",
    "club": "Hull KR",
    "teamName": "Hull KR Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.753953,
    "lng": -0.2648195,
    "groundName": "Sewell Group Craven Park",
    "groundLabel": "Sewell Group Craven Park",
    "groundRole": "primary",
    "notes": null,
    "website": "https://hullkr.co.uk/foundation/female-rugby",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "DEW-RF--1-XRVF",
    "club": "Dewsbury Moor",
    "teamName": "Dewsbury Moor Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.6963156,
    "lng": -1.6590452,
    "groundName": "Dewsbury Moor Sports Club",
    "groundLabel": "Dewsbury Moor Sports Club",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/dewsburymoorgirlsarlfc/",
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "STA-RF--1-MBZG",
    "club": "Stanningley",
    "teamName": "Stanningley Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.8176971,
    "lng": -1.6577723,
    "groundName": "The Arthur Miller Stadium",
    "groundLabel": "The Arthur Miller Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.stanningleyrugby.co.uk/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "OUL-RF--1-IDKM",
    "club": "Oulton Raidettes",
    "teamName": "Oulton Raidettes Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.7426528,
    "lng": -1.4503313,
    "groundName": "Oulton & Woodlesford Sports & Social Club",
    "groundLabel": "Oulton & Woodlesford Sports & Social Club",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.facebook.com/oulton.raidettes/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "SHE-RF--1-PXQV",
    "club": "Sheffield Eagles",
    "teamName": "Sheffield Eagles Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-YH",
    "regionName": "Yorkshire & Humber",
    "lat": 53.4065643,
    "lng": -1.386863,
    "groundName": "Sheffield Hallam University Sports Park",
    "groundLabel": "Sheffield Hallam University Sports Park",
    "groundRole": "primary",
    "notes": "Most regularly played home ground (seem to play occasionally at other grounds)",
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "COV-RF--1-3XRO",
    "club": "Coventry Bears",
    "teamName": "Coventry Bears Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-WM",
    "regionName": "West Midlands",
    "lat": 52.4039074,
    "lng": -1.5568396,
    "groundName": "Old Coventrians Rugby Football Club",
    "groundLabel": "Old Coventrians Rugby Football Club",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.coventrybears.com/womens",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LEA-RF--1-R2RG",
    "club": "Leamington Royals",
    "teamName": "Leamington Royals Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-WM",
    "regionName": "West Midlands",
    "lat": 52.3186841,
    "lng": -1.54057,
    "groundName": "Leamington Rugby Football Club",
    "groundLabel": "Leamington Rugby Football Club",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.facebook.com/people/Leamington-Royals-Ladies-Rugby-League/100087282506305",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "NOT-RF--1-PV4G",
    "club": "Nottingham Outlaws",
    "teamName": "Nottingham Outlaws Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-EM",
    "regionName": "East Midlands",
    "lat": 52.9233282,
    "lng": -1.1710377,
    "groundName": "Lenton Lane",
    "groundLabel": "Lenton Lane",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.nottinghamrl.co.uk/women/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "TEL-RF--2-TU42",
    "club": "Telford Raiders",
    "teamName": "Telford Raiders Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-WM",
    "regionName": "West Midlands",
    "lat": 52.6676884,
    "lng": -2.4481823,
    "groundName": "Telford Hornets Rugby Club RFC",
    "groundLabel": "Telford Hornets Rugby Club RFC",
    "groundRole": "primary",
    "notes": null,
    "website": "https://telford-raiders.com/womens/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "ARM-RF--0-T059",
    "club": "Army RL",
    "teamName": "Army RL Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-SE",
    "regionName": "South East",
    "lat": 51.2631164,
    "lng": -0.7557127,
    "groundName": "The Army Athletic Association",
    "groundLabel": "The Army Athletic Association",
    "groundRole": "primary",
    "notes": "Individual match locations seem to vary",
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BED-RF--0-B30S",
    "club": "Bedford Tigers",
    "teamName": "Bedford Tigers Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-EE",
    "regionName": "East of England",
    "lat": 52.1594256,
    "lng": -0.4380077,
    "groundName": "Bedford Athletic Rugby Club (",
    "groundLabel": "Bedford Athletic Rugby Club (",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.rugby-league.com/club-profile/24005/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "CAR-RF--3-B3SW",
    "club": "Cardiff Demons",
    "teamName": "Cardiff Demons Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "WLS",
    "regionName": "Wales",
    "lat": 51.4798026,
    "lng": -3.1845185,
    "groundName": "Cardiff Arms Park",
    "groundLabel": "Cardiff Arms Park",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.cardiffdemons.com/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LON-RF--0-BUBQ",
    "club": "London Broncos",
    "teamName": "London Broncos Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier2",
    "division": "RFL Women's Championship",
    "country": "ENG",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.4648499,
    "lng": -0.2458613,
    "groundName": "Rosslyn Park FC",
    "groundLabel": "Rosslyn Park FC",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.londonbroncosladies.com/",
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BRE-LO-0.-81XN",
    "club": "Brentwood Eels",
    "teamName": "Brentwood Eels Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-EE",
    "regionName": "East of England",
    "lat": 51.649105,
    "lng": 0.2750967,
    "groundName": "The Old Brentwoods Club",
    "groundLabel": "The Old Brentwoods Club",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "NOR-LO--0-6E4D",
    "club": "North Herts Crusaders",
    "teamName": "North Herts Crusaders Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-EE",
    "regionName": "East of England",
    "lat": 51.9601232,
    "lng": -0.2815424,
    "groundName": "King George's Play Area",
    "groundLabel": "King George's Play Area",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BED-LO--0-MO0W",
    "club": "Bedford Tigers",
    "teamName": "Bedford Tigers Development Team Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-EE",
    "regionName": "East of England",
    "lat": 52.1594256,
    "lng": -0.4380077,
    "groundName": "Bedford Athletic Rugby Club",
    "groundLabel": "Bedford Athletic Rugby Club",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "ANG-LO-1.-Y1S8",
    "club": "Anglian Vipers",
    "teamName": "Anglian Vipers Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-EE",
    "regionName": "East of England",
    "lat": 52.5900641,
    "lng": 1.1401406,
    "groundName": "Wymondham Rugby Football Club",
    "groundLabel": "Wymondham Rugby Football Club",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "ELM-LO--0-J8IL",
    "club": "Elmbridge Eagles",
    "teamName": "Elmbridge Eagles Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-SE",
    "regionName": "South East",
    "lat": 51.382502,
    "lng": -0.3413272,
    "groundName": "Old Cranleighan Rugby Club",
    "groundLabel": "Old Cranleighan Rugby Club",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "LON-LO--0-DESV",
    "club": "London Broncos",
    "teamName": "London Broncos Development Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-LON",
    "regionName": "London",
    "lat": 51.4650099,
    "lng": -0.2456406,
    "groundName": "Rosslyn Park FC",
    "groundLabel": "Rosslyn Park FC",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BRI-LO--0-1Y4Z",
    "club": "Brighton and Hove",
    "teamName": "Brighton and Hove Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-SE",
    "regionName": "South East",
    "lat": 50.8587848,
    "lng": -0.0875045,
    "groundName": "University of Brighton Falmer campus",
    "groundLabel": "University of Brighton Falmer campus",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "GOL-LO--2-7U1D",
    "club": "Golden Ferns",
    "teamName": "Golden Ferns Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-SW",
    "regionName": "South West",
    "lat": 51.5487765,
    "lng": -2.5734694,
    "groundName": "Oaklands",
    "groundLabel": "Oaklands",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "BAT-LO--2-XCL5",
    "club": "Bath Bees",
    "teamName": "Bath Bees Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-SW",
    "regionName": "South West",
    "lat": 51.361618,
    "lng": -2.3773469,
    "groundName": "Odd Down Sports Ground",
    "groundLabel": "Odd Down Sports Ground",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/bathbeesrugbyleague",
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": "THA-LO--2-BIVU",
    "club": "Thatto Heath",
    "teamName": "Thatto Heath Women",
    "sport": "rugby",
    "code": "league",
    "tier": "tier3",
    "division": "Local League",
    "country": "ENG",
    "regionCode": "ENG-NW",
    "regionName": "North West",
    "lat": 53.432827,
    "lng": -2.7493143,
    "groundName": "Thatto Heath Crusaders Rugby League Club",
    "groundLabel": "Thatto Heath Crusaders Rugby League Club",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "streaming": null,
    "otherSocials": null
  }
];
