// teams.js
// This file contains the list of clubs shown on the map.
// Add, remove, or edit entries here as needed.

const teams = [
  {
    "id": "",
    "club": "Arsenal",
    "teamName": "Arsenal Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Emirates Stadium",
    "groundLabel": "Arsenal - Emirates Stadium",
    "groundRole": "primary",
    "notes": "Arsenal's primary stadium (2024/25)",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.55572979999999,
    "lng": -0.1083118
  },
  {
    "id": "",
    "club": "Arsenal",
    "teamName": "Arsenal Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Borehamwood Football Club",
    "groundLabel": "Arsenal - Borehamwood Football Club ",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.6621617,
    "lng": -0.2712835
  },
  {
    "id": "",
    "club": "Aston Villa",
    "teamName": "Aston Villa Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Villa Park",
    "groundLabel": "Aston Villa - Villa Park",
    "groundRole": "primary",
    "notes": "Aston VIlla's primary stadium for WSL home games. Other home games at Bescot Stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 52.50911170000001,
    "lng": -1.8847828
  },
  {
    "id": "",
    "club": "Aston Villa",
    "teamName": "Aston Villa Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Walsall FC Poundland Bescot Stadium",
    "groundLabel": "Aston Villa - Walsall FC Poundland Bescot Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 52.5657831,
    "lng": -1.9906229
  },
  {
    "id": "",
    "club": "Brighton & Hove Albion",
    "teamName": "Brighton & Hove Albion Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Broadfield Stadium",
    "groundLabel": "Brighton & Hove Albion - Broadfield Stadium",
    "groundRole": "primary",
    "notes": "Main stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.09980700000001,
    "lng": -0.1948115
  },
  {
    "id": "",
    "club": "Brighton & Hove Albion",
    "teamName": "Brighton & Hove Albion Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "American Express Stadium",
    "groundLabel": "Brighton & Hove Albion - American Express Stadium",
    "groundRole": "secondary",
    "notes": "Brighton Women's second ground - Select games played here",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 50.86157240000001,
    "lng": -0.0836618
  },
  {
    "id": "",
    "club": "Chelsea",
    "teamName": "Chelsea Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Kingsmeadow",
    "groundLabel": "Chelsea - Kingsmeadow",
    "groundRole": "primary",
    "notes": "Chelsea's primary stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.40526699999999,
    "lng": -0.2818903
  },
  {
    "id": "",
    "club": "Chelsea",
    "teamName": "Chelsea Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Stamford Bridge",
    "groundLabel": "Chelsea - Stamford Bridge",
    "groundRole": "primary",
    "notes": "Select games played here",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.4817241,
    "lng": -0.1909471
  },
  {
    "id": "",
    "club": "Crystal Palace -  VBS Community Stadium",
    "teamName": "Crystal Palace -  VBS Community Stadium Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Crystal Palace -  VBS Community Stadium",
    "groundLabel": "Crystal Palace -  VBS Community Stadium",
    "groundRole": "primary",
    "notes": "Crystal Palace primary stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.3677754,
    "lng": -0.2042941
  },
  {
    "id": "",
    "club": "Crystal Palace",
    "teamName": "Crystal Palace Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Selhurst Park",
    "groundLabel": "Crystal Palace - Selhurst Park",
    "groundRole": "primary",
    "notes": "Select games played here",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.3981495,
    "lng": -0.0857056
  },
  {
    "id": "",
    "club": "Everton",
    "teamName": "Everton Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Walton Hall Park",
    "groundLabel": "Everton - Walton Hall Park",
    "groundRole": "primary",
    "notes": "Everton Women's main stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 53.445356,
    "lng": -2.9536821
  },
  {
    "id": "",
    "club": "Everton",
    "teamName": "Everton Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Goodison Park",
    "groundLabel": "Everton - Goodison Park",
    "groundRole": "secondary",
    "notes": "Everton Women's second stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 53.4388437,
    "lng": -2.9662821
  },
  {
    "id": "",
    "club": "Leicester City",
    "teamName": "Leicester City Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "King Power Stadium",
    "groundLabel": "Leicester City - King Power Stadium",
    "groundRole": "primary",
    "notes": "Primary stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 52.62036620000001,
    "lng": -1.1421895
  },
  {
    "id": "",
    "club": "Leicester City",
    "teamName": "Leicester City Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Pirelli Stadium Princess Way",
    "groundLabel": "Leicester City - Pirelli Stadium Princess Way",
    "groundRole": "secondary",
    "notes": "Secondary stadium - When scheduling clashes occur",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 52.8215623,
    "lng": -1.627267
  },
  {
    "id": "",
    "club": "Liverpool",
    "teamName": "Liverpool Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Totally Wicked Stadium",
    "groundLabel": "Liverpool - Totally Wicked Stadium",
    "groundRole": "primary",
    "notes": "Liverpool Women's main stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 53.4474676,
    "lng": -2.7261145
  },
  {
    "id": "",
    "club": "Liverpool",
    "teamName": "Liverpool Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Anfield",
    "groundLabel": "Liverpool - Anfield",
    "groundRole": "secondary",
    "notes": "Liverpool Women's secondary stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 53.43084349999999,
    "lng": -2.9608174
  },
  {
    "id": "",
    "club": "Manchester City",
    "teamName": "Manchester City Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Joie Stadium",
    "groundLabel": "Manchester City - Joie Stadium",
    "groundRole": "primary",
    "notes": "Manchester City Women's main stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 53.48096770000001,
    "lng": -2.1926539
  },
  {
    "id": "",
    "club": "Manchester City",
    "teamName": "Manchester City Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Etihad Stadium",
    "groundLabel": "Manchester City - Etihad Stadium",
    "groundRole": "secondary",
    "notes": "Manchester City Women's secondary stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 53.4831634,
    "lng": -2.2003736
  },
  {
    "id": "",
    "club": "Manchester United",
    "teamName": "Manchester United Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Leigh Sports Village",
    "groundLabel": "Manchester United - Leigh Sports Village",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.manutd.com/en/news/women",
    "instagram": null,
    "twitter": null,
    "lat": 53.48995319999999,
    "lng": -2.5309793
  },
  {
    "id": "",
    "club": "Manchester United",
    "teamName": "Manchester United Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Old Trafford",
    "groundLabel": "Manchester United - Old Trafford",
    "groundRole": "primary",
    "notes": "Selected matches played here",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 53.46305889999999,
    "lng": -2.2913401
  },
  {
    "id": "",
    "club": "Tottenham Hotspur",
    "teamName": "Tottenham Hotspur Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Brisbane Lane",
    "groundLabel": "Tottenham Hotspur - Brisbane Lane",
    "groundRole": "primary",
    "notes": "Gaughan Group Stadium",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.5601583,
    "lng": -0.0126087
  },
  {
    "id": "",
    "club": "Tottenham Hotspurs",
    "teamName": "Tottenham Hotspurs Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Tottenham Hotspur Stadium",
    "groundLabel": "Tottenham Hotspurs - Tottenham Hotspur Stadium",
    "groundRole": "primary",
    "notes": "Select games played here",
    "website": null,
    "instagram": null,
    "twitter": null,
    "lat": 51.60422049999999,
    "lng": -0.06622309999999998
  },
  {
    "id": "",
    "club": "West Ham Women",
    "teamName": "West Ham Women Women",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "ENG",
    "regionCode": "",
    "regionName": "",
    "groundName": "Chigwell Construction Stadium",
    "groundLabel": "West Ham Women - Chigwell Construction Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.whufc.com/women/womens-team",
    "instagram": null,
    "twitter": null,
    "lat": 51.5473022,
    "lng": 0.1600155
  } //add teams below as needed
];
