// teams.js
// This file contains the list of clubs shown on the map.
// Add, remove, or edit entries here as needed.

const teams = [
  {
    "id": null,
    "club": "Arsenal",
    "teamName": "Arsenal WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.5557298,
    "lng": -0.1083118,
    "groundName": "Emirates Stadium",
    "groundLabel": "Emirates Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.arsenal.com/women",
    "instagram": "https://www.instagram.com/arsenalwfc/",
    "twitter": "https://x.com/ArsenalWFC",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Arsenal",
    "teamName": "Arsenal WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.6621617,
    "lng": -0.2712835,
    "groundName": "Borehamwood Football Club",
    "groundLabel": "Borehamwood Football Club",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.arsenal.com/women",
    "instagram": "https://www.instagram.com/arsenalwfc/",
    "twitter": "https://x.com/ArsenalWFC",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Aston Villa",
    "teamName": "Aston Villa WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 52.5091117,
    "lng": -1.8847828,
    "groundName": "Villa Park",
    "groundLabel": "Villa Park",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.avfc.co.uk/Teams/womens/",
    "instagram": "https://www.instagram.com/avwfcofficial/",
    "twitter": "https://x.com/AVWFCOfficial",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Aston Villa",
    "teamName": "Aston Villa WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 52.5657831,
    "lng": -1.9906229,
    "groundName": "Bescot Stadium",
    "groundLabel": "Walsall FC Poundland Bescot Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.avfc.co.uk/Teams/womens/",
    "instagram": "https://www.instagram.com/avwfcofficial/",
    "twitter": "https://x.com/AVWFCOfficial",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Brighton & Hove Albion",
    "teamName": "Brighton & Hove Albion WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.099807,
    "lng": -0.1948115,
    "groundName": "Broadfield Stadium",
    "groundLabel": "Broadfield Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.brightonandhovealbion.com/teams/womens-team",
    "instagram": "https://www.instagram.com/bhafcwomen/",
    "twitter": "https://x.com/BHAFCWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Brighton & Hove Albion",
    "teamName": "Brighton & Hove Albion WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 50.8615724,
    "lng": -0.0836618,
    "groundName": "American Express Stadium",
    "groundLabel": "American Express Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.brightonandhovealbion.com/teams/womens-team",
    "instagram": "https://www.instagram.com/bhafcwomen/",
    "twitter": "https://x.com/BHAFCWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Chelsea",
    "teamName": "Chelsea WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.405267,
    "lng": -0.2818903,
    "groundName": "Kingsmeadow",
    "groundLabel": "Kingsmeadow",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.chelseafc.com/en/teams/chelsea-women",
    "instagram": "https://www.instagram.com/chelseafcw/",
    "twitter": "https://x.com/ChelseaFCW",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Chelsea",
    "teamName": "Chelsea WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.4817241,
    "lng": -0.1909471,
    "groundName": "Stamford Bridge",
    "groundLabel": "Stamford Bridge",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.chelseafc.com/en/teams/chelsea-women",
    "instagram": "https://www.instagram.com/chelseafcw/",
    "twitter": "https://x.com/ChelseaFCW",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Crystal Palace",
    "teamName": "Crystal Palace WFC",
    "sport": "football",
    "tier": "tier2",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.3677754,
    "lng": -0.2042941,
    "groundName": "VBS Community Stadium",
    "groundLabel": "Crystal Palace -Â  VBS Community Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.cpfc.co.uk/palace-women/",
    "instagram": "https://www.instagram.com/cpfc_w/",
    "twitter": "https://x.com/cpfc_w",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Crystal Palace",
    "teamName": "Crystal Palace WFC",
    "sport": "football",
    "tier": "tier2",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.3981495,
    "lng": -0.0857056,
    "groundName": "Selhurst Park",
    "groundLabel": "Selhurst Park",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.cpfc.co.uk/palace-women/",
    "instagram": "https://www.instagram.com/cpfc_w/",
    "twitter": "https://x.com/cpfc_w",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Everton",
    "teamName": "Everton WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.445356,
    "lng": -2.9536821,
    "groundName": "Walton Hall Park",
    "groundLabel": "Walton Hall Park",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.evertonfc.com/women",
    "instagram": "https://www.instagram.com/evertonwomen/",
    "twitter": "https://x.com/EvertonWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Everton",
    "teamName": "Everton WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.4388437,
    "lng": -2.9662821,
    "groundName": "Goodison Park",
    "groundLabel": "Goodison Park",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.evertonfc.com/women",
    "instagram": "https://www.instagram.com/evertonwomen/",
    "twitter": "https://x.com/EvertonWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Leicester City",
    "teamName": "Leicester City WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 52.6203662,
    "lng": -1.1421895,
    "groundName": "King Power Stadium",
    "groundLabel": "King Power Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.lcfc.com/women",
    "instagram": "https://www.instagram.com/lcfcwomen/",
    "twitter": "https://x.com/LCFC_Women",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Leicester City",
    "teamName": "Leicester City WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 52.8215623,
    "lng": -1.627267,
    "groundName": "Pirelli Stadium Princess Way",
    "groundLabel": "Pirelli Stadium Princess Way",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.lcfc.com/women",
    "instagram": "https://www.instagram.com/lcfcwomen/",
    "twitter": "https://x.com/LCFC_Women",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Liverpool",
    "teamName": "Liverpool WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.4474676,
    "lng": -2.7261145,
    "groundName": "Totally Wicked Stadium",
    "groundLabel": "Totally Wicked Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.liverpoolfc.com/team/womens",
    "instagram": "https://www.instagram.com/liverpoolfcw/",
    "twitter": "https://x.com/LiverpoolFCW",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Liverpool",
    "teamName": "Liverpool WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.4308435,
    "lng": -2.9608174,
    "groundName": "Anfield",
    "groundLabel": "Anfield",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.liverpoolfc.com/team/womens",
    "instagram": "https://www.instagram.com/liverpoolfcw/",
    "twitter": "https://x.com/LiverpoolFCW",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Manchester City",
    "teamName": "Manchester City WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.4809677,
    "lng": -2.1926539,
    "groundName": "Joie Stadium",
    "groundLabel": "Joie Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.mancity.com/manchester-city-women",
    "instagram": "https://www.instagram.com/mancitywomen",
    "twitter": "https://x.com/ManCityWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Manchester City",
    "teamName": "Manchester City WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.4831634,
    "lng": -2.2003736,
    "groundName": "Etihad Stadium",
    "groundLabel": "Etihad Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.mancity.com/manchester-city-women",
    "instagram": "https://www.instagram.com/mancitywomen",
    "twitter": "https://x.com/ManCityWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Manchester United",
    "teamName": "Manchester United WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.4899532,
    "lng": -2.5309793,
    "groundName": "Leigh Sports Village",
    "groundLabel": "Leigh Sports Village",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.manutd.com/en/news/women",
    "instagram": "https://www.instagram.com/manutdwomen/",
    "twitter": "https://x.com/ManUtdWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Manchester United",
    "teamName": "Manchester United WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.4630589,
    "lng": -2.2913401,
    "groundName": "Old Trafford",
    "groundLabel": "Old Trafford",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.manutd.com/en/news/women",
    "instagram": "https://www.instagram.com/manutdwomen/",
    "twitter": "https://x.com/ManUtdWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Tottenham Hotspur",
    "teamName": "Tottenham Hotspur WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.5601583,
    "lng": -0.0126087,
    "groundName": "Brisbane Lane",
    "groundLabel": "Brisbane Lane",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.tottenhamhotspur.com/teams/women/players/",
    "instagram": "https://www.instagram.com/spurswomen/",
    "twitter": "https://x.com/SpursWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "Tottenham Hotspurs",
    "teamName": "Tottenham Hotspurs WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.6042205,
    "lng": -0.0662231,
    "groundName": "Tottenham Hotspur Stadium",
    "groundLabel": "Tottenham Hotspur Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": "https://www.tottenhamhotspur.com/teams/women/players/",
    "instagram": "https://www.instagram.com/spurswomen/",
    "twitter": "https://x.com/SpursWomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "West Ham Women",
    "teamName": "West Ham WFC",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.5473022,
    "lng": 0.1600155,
    "groundName": "Chigwell Construction Stadium",
    "groundLabel": "Chigwell Construction Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.whufc.com/women/womens-team",
    "instagram": "https://www.instagram.com/westhamwomen/",
    "twitter": "https://x.com/westhamwomen",
    "streaming": null,
    "otherSocials": null
  },
  {
    "id": null,
    "club": "London City Lionesses",
    "teamName": "London City Lionesses",
    "sport": "football",
    "tier": "tier1",
    "division": "WSL",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.39046639,
    "lng": 0.021316266,
    "groundName": "Copperjax Community Stadium",
    "groundLabel": "Copperjax Community Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": "https://www.londoncitylionesses.com/",
    "instagram": "https://www.instagram.com/londoncitylionesses/",
    "twitter": "https://twitter.com/LC_Lionesses",
    "streaming": null,
    "otherSocials": "https://www.youtube.com/@londoncitylionesses, https://www.facebook.com/LondonCityLionesses, https://www.tiktok.com/@londoncitylionesses"
  },
  {
    "id": null,
    "club": "Bristol Bears",
    "teamName": "Bristol Bears Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.4980888,
    "lng": -2.5299069,
    "groundName": "Shaftesbury Park",
    "groundLabel": "Shaftesbury Park",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/bristolbearswomen/",
    "twitter": "https://twitter.com/BristolBearsW",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/BristolBearsW"
  },
  {
    "id": null,
    "club": "Exeter Chiefs",
    "teamName": "Exeter Chiefs Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 50.7095567,
    "lng": -3.4683403,
    "groundName": "Sandy Park",
    "groundLabel": "Sandy Park",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/exechiefswomen/",
    "twitter": "https://twitter.com/ExeChiefsWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/ExeterChiefsWomen"
  },
  {
    "id": null,
    "club": "Ealing Trailfinders",
    "teamName": "Ealing Trailfinders Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.5247325,
    "lng": -0.3293985,
    "groundName": "Ealing Trailfinders Rugby Club",
    "groundLabel": "Ealing Trailfinders Rugby Club",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/trailfinderswomen/",
    "twitter": "https://twitter.com/TrailfindersW",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/EalingTrailfindersWomensRugby"
  },
  {
    "id": null,
    "club": "Gloucester-Hartpury",
    "teamName": "Gloucester-Hartpury Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.9037018,
    "lng": -2.3025382,
    "groundName": "The Hartpury Arena",
    "groundLabel": "The Hartpury Arena",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/gloucesterhartpury",
    "twitter": "https://twitter.com/gloshartpury",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/gloucesterhartpury/"
  },
  {
    "id": null,
    "club": "Gloucester-Hartpury",
    "teamName": "Gloucester-Hartpury Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.8711897,
    "lng": -2.2428512,
    "groundName": "Kingsholm Stadium",
    "groundLabel": "Kingsholm Stadium",
    "groundRole": "secondary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/gloucesterhartpury",
    "twitter": "https://twitter.com/gloshartpury",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/gloucesterhartpury/"
  },
  {
    "id": null,
    "club": "Harlequins",
    "teamName": "Harlequins Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.4504131,
    "lng": -0.3441495,
    "groundName": "Twickenham Stoop",
    "groundLabel": "Twickenham Stoop",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/harlequinswomen/",
    "twitter": "https://twitter.com/HarlequinsWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/harlequinsladies"
  },
  {
    "id": null,
    "club": "Harlequins",
    "teamName": "Harlequins Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.2353024,
    "lng": -0.6071427,
    "groundName": "Surrey Sports Park",
    "groundLabel": "Surrey Sports Park",
    "groundRole": "secondary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/harlequinswomen/",
    "twitter": "https://twitter.com/HarlequinsWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/harlequinsladies"
  },
  {
    "id": null,
    "club": "Leicester Tigers",
    "teamName": "Leicester Tigers Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 52.6241667,
    "lng": -1.1330556,
    "groundName": "Mattioli Woods Welford Road Stadium",
    "groundLabel": "Mattioli Woods Welford Road Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/tigerswomens",
    "twitter": "https://twitter.com/TigersWomens",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/tigerswomens"
  },
  {
    "id": null,
    "club": "Loughborough Lightning",
    "teamName": "Loughborough Lightning Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 52.2396946,
    "lng": -0.919472,
    "groundName": "cinch Stadium",
    "groundLabel": "cinch Stadium at Franklin's Gardens",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/lightningrugby/",
    "twitter": "https://twitter.com/LightningRugby",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/LightningRugby"
  },
  {
    "id": null,
    "club": "Sale Sharks Women",
    "teamName": "Sale Sharks Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 53.4160883,
    "lng": -2.3212665,
    "groundName": "Heywood Road",
    "groundLabel": "Heywood Road",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/salesharkswomen/",
    "twitter": "https://twitter.com/SaleSharksWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/salesharkswomen"
  },
  {
    "id": null,
    "club": "Saracens",
    "teamName": "Saracens Women",
    "sport": "rugby union",
    "tier": "tier1",
    "division": "Premiership",
    "country": "England",
    "regionCode": null,
    "regionName": null,
    "lat": 51.6030216,
    "lng": -0.2235209,
    "groundName": "StoneX Stadium",
    "groundLabel": "StoneX Stadium",
    "groundRole": "primary",
    "notes": null,
    "website": null,
    "instagram": "https://www.instagram.com/saracenswomen/",
    "twitter": "https://twitter.com/SaracensWomen",
    "streaming": null,
    "otherSocials": "https://www.facebook.com/saracenswomen"
  }
];

